# Use root/example as user/password credentials
version: '3.1'

services:
  database:
    image: mongo:4.0
    restart: always
    container_name: template-mongodb
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
      MONGO_INITDB_DATABASE: template
